# Uncomment this line to define a global platform for your project
# platform :ios, '6.0'

source 'https://github.com/CocoaPods/Specs.git'

target 'Simple Sharing' do

pod "Facebook-iOS-SDK"

end

target 'Simple SharingTests' do

end

